### ISSUE TITLE
Don't pack single files in tar

### ISSUE THREAD

**Issue by dereulenspiegel** [Stouts/Stouts.openvpn#21]
Hi!

Really great role. We use it a lot. Some Linux users have complained that the generated tar archive contains only files and not a folder containing files. So it would be nice to put the files in folder named like the archive and then create an archive of the folder. Just a detail.

Thanks!

**Comment by conorsch** [comment]
@dereulenspiegel This has bothered me for a while too, but the role is so otherwise so strong I've put up with it. As you may have noticed, as of #44 the role is now using zip rather than tar, but the lack of a nested directory still persists, so your initial objection is still valid.

Does anyone else have strong feelings here?

**Comment by xahare** [comment]
Ive been using this role for years, and this has also bugged me. never thought to bring it up till i saw this thread.

**Comment by conorsch** [comment]
Given that the role now uses zip rather than tar archives, we're stuck with the current unnested behavior. (Reading through `man zip` didn't show any relevant options here to change the behavior.) Rather than complicate the role with extra tasks to copy files to temporary directories prior to zipping, let's accept this minor limitation and focus on other issues.
