### ISSUE TITLE
Role must be run as root

### ISSUE THREAD

**Issue by coreoas** [Stouts/Stouts.openvpn#51]
Since there are no `become=yes` in tasks that requires sudo privileges, the whole role must be run as a superuser.

Is it possible to make it so that an unprivileged user could run this role.

Tharks !

**Comment by conorsch** [comment]
An interesting request. I tend to prefer judicious use of `become:` at the task-level, but it seems to go against the grain of most of the Ansible community. Can you explain your use case in more depth, @coreoas?

**Comment by sean-abbott** [comment]
Well, as of right now, I have to run the whole role as root, because within the role, things like the package installs aren't run with "become".

I agree with you; I'd rather just the tasks that need privileges use "become", but, when calling the role (if I want to not edit the role, which I don't), I had to use become at the play level because:

```
TASK [Stouts.openvpn : Install requirements (Debian)] **************************
failed: [54.210.29.69] (item=[u'openvpn', u'udev', u'openssl', u'zip']) => {"cmd": "apt-get update", "failed": true, "item": ["openvpn", "udev", "openssl", "zip"], "msg": "W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\nE: Unable to lock directory /var/lib/apt/lists/\nW: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)\nW: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)\nE: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?", "rc": 100, "stderr": "W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\nE: Unable to lock directory /var/lib/apt/lists/\nW: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)\nW: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)\nE: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\n", "stdout": "", "stdout_lines": []}
```

**Comment by nkakouros** [comment]
Is there any benefit in doing this? Is it just a matter of not wanting to add `become: yes` to the play level?

**Comment by sean-abbott** [comment]
My personal experience has been that having a per-task become is better than doing one for the entire play because I have found it is A) more explicit (pythonically, explicit > implicit), and because there are a number of times when it is preferable to not run everything as root. So I don't like the habit of just using "become" at the play level when calling a role.

It is, however, personal preference and I'm sure there are effective arguments on the other side, so <shrug>.

**Comment by nkakouros** [comment]
Ok, I 'll see if I can pinpoint the tasks that need `become: yes`.

**Comment by nkakouros** [comment]
Actually, looking at the tasks the role runs, 90% of the tasks need to be run as root. If I am wrong, please correct me. I don't think it is worth making the code more verbose and the work hours to implement this.
